language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-package=test && coverage report
 after_success:
  - coveralls
